version: '2'
services: 
  datastore_timeseries_database:
    build: database
    ports: 
          - "8086"  

  datastore_timeseries_app:
    build: app
    links : 
          - datastore_timeseries_database
    ports: 
          - "8080:8080"

    